//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTemplatePro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTemplatePro.Resources.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Link.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string btnCompress {
            get {
                return ResourceManager.GetString("btnCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string btnDeleteAll {
            get {
                return ResourceManager.GetString("btnDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string btnFolder {
            get {
                return ResourceManager.GetString("btnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string btnOpenFile {
            get {
                return ResourceManager.GetString("btnOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string clh2 {
            get {
                return ResourceManager.GetString("clh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string clh3 {
            get {
                return ResourceManager.GetString("clh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string clh4 {
            get {
                return ResourceManager.GetString("clh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string clh5 {
            get {
                return ResourceManager.GetString("clh5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string clh6 {
            get {
                return ResourceManager.GetString("clh6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creart Date.
        /// </summary>
        internal static string clh7 {
            get {
                return ResourceManager.GetString("clh7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cmdExit1 {
            get {
                return ResourceManager.GetString("cmdExit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compres File.
        /// </summary>
        internal static string copressFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("copressFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string englishToolStripMenuItem {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List File.
        /// </summary>
        internal static string gbListFile {
            get {
                return ResourceManager.GetString("gbListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Website.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link download website.
        /// </summary>
        internal static string lblLinkWeb {
            get {
                return ResourceManager.GetString("lblLinkWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File HTML.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string lblProgress {
            get {
                return ResourceManager.GetString("lblProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Folder.
        /// </summary>
        internal static string lblSaveAs {
            get {
                return ResourceManager.GetString("lblSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        internal static string removeAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("removeAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        internal static string removeFIleToolStripMenuItem {
            get {
                return ResourceManager.GetString("removeFIleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Singe.
        /// </summary>
        internal static string removeSingeToolStripMenuItem {
            get {
                return ResourceManager.GetString("removeSingeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string smiOpen {
            get {
                return ResourceManager.GetString("smiOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string toolStripMenuItem3 {
            get {
                return ResourceManager.GetString("toolStripMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string tsmiBG {
            get {
                return ResourceManager.GetString("tsmiBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background 1.
        /// </summary>
        internal static string tsmiBG1 {
            get {
                return ResourceManager.GetString("tsmiBG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background 2.
        /// </summary>
        internal static string tsmiBG2 {
            get {
                return ResourceManager.GetString("tsmiBG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background 3.
        /// </summary>
        internal static string tsmiBG3 {
            get {
                return ResourceManager.GetString("tsmiBG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background 4.
        /// </summary>
        internal static string tsmiBG4 {
            get {
                return ResourceManager.GetString("tsmiBG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tsmiFB {
            get {
                return ResourceManager.GetString("tsmiFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string tsmiFile {
            get {
                return ResourceManager.GetString("tsmiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string tsmiLang {
            get {
                return ResourceManager.GetString("tsmiLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string tsmiOpenF {
            get {
                return ResourceManager.GetString("tsmiOpenF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string tsmiSetting {
            get {
                return ResourceManager.GetString("tsmiSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Nodepad.
        /// </summary>
        internal static string usingNodepadToolStripMenuItem {
            get {
                return ResourceManager.GetString("usingNodepadToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string vietnameseToolStripMenuItem {
            get {
                return ResourceManager.GetString("vietnameseToolStripMenuItem", resourceCulture);
            }
        }
    }
}
